config/routes.rb
Rails.application.routes.draw do
  resources :records

  get '/stats', action: :index, controller: 'stats'
  get '/s/:id' => "shortener/shortened_urls#show"

  get '/urls/new' => 'shortener_new_urls#new'
  post '/urls/new' => 'shortener_new_urls#create'

  get '/' => 'main#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :set_record, only: %i[ show edit update destroy ]

  # GET /
  def index   
    AMQP::Queue.enqueue :record, to_payload, {}
    
    if request.query_parameters[:url]
      redirect_to request.query_parameters[:url], :status => 301
    else
      respond_to do |format|
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: request.referrer, status: :unprocessable_entity }
      end
    end
  end

  private

    def remote_ip
      # default behaviour, IP from HTTP_X_FORWARDED_FOR
      ip = request.env["HTTP_X_FORWARDED_FOR"]
      ip ||= request.env['action_dispatch.remote_ip'].to_s
  
      if TrackingApp::App.config.gateway == 'akamai'
        # custom header that contains only client IP
        true_client_ip = request.env['HTTP_TRUE_CLIENT_IP'].to_s
        # take IP from TRUE_CLIENT_IP only if its not nil or empty
        ip = true_client_ip unless true_client_ip.nil? || true_client_ip.empty?
      end
  
      Rails.logger.debug "User login IP address: #{ip}"
      return ip
    end

    def to_payload
      {
        uuid: request.env['action_dispatch.request_id'].to_s,
        ip: remote_ip,
        visited_at: Time.current,
        http_sec: request.env.each_pair.with_object({}) do |(key,value), http_sec|
          http_sec[key.delete_prefix('HTTP_SEC_').downcase] = value if key.match? /HTTP_SEC/
        end,
        referrer: request.referrer,
        url: request.query_parameters[:url],
        language: request.accept_language
      }
    end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: %i[ show edit update destroy ]

  # GET /records or /records.json
  def index   
    @records = Record.all
  end

  # GET /records/1 or /records/1.json
  def show
    @record = Record.find(params[:id])
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records or /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to record_url(@record), notice: "Record was successfully created." }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1 or /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to record_url(@record), notice: "Record was successfully updated." }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1 or /records/1.json
  def destroy
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url, notice: "Record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def record_params
      params.fetch(:record, {})
    end
end

app/controllers/shortener_new_urls_controller.rb
class ShortenerNewUrlsController < ApplicationController
  # GET /urls
  def new
    @shortened_url = Shortener::ShortenedUrl.new url: params[:url]
  end

  def create
    @shortened_url = Shortener::ShortenedUrl.generate "https://tracking-app.papievis.com/?url=#{URI.encode(params.dig :shortened_url, :url)}"

    respond_to do |format|
      format.html { redirect_to "https://tracking-app.papievis.com/s/#{@shortened_url.unique_key}", notice: "Record was successfully created." }
      format.json { render :show, status: :created, location: @shortened_url }
    end
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  # GET /records or /records.json
  def index
    @records = Record.group(:url).count
    @records['unknown'] = @records.delete nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<p id="error">Unprocessable entity</p>

<h1>Referrer</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= link_to 'Referrer', request.referrer %></td>
    </tr>
  </tbody>
</table>

app/views/records/_form.html.erb
<%= form_with(model: record, local: true) do |form| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Records</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>


<h1>Records</h1>

<table>
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @record.as_json.each do |k,v| %>
      <tr>
        <td><%= k %></td>
        <td><%= v %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>

app/views/shortener_new_urls/_form.html.erb
<%= form_for :shortened_url, :url => { :action => "create" }  do |form| %>
  Url: <%= form.text_field :url, style: 'width: 400px;' %><br />

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shortener_new_urls/new.html.erb
<h1>New Url</h1>

<%= render 'form', record: @record %>

app/views/shortener_new_urls/show.html.erb
<p id="notice"><%= notice %></p>


<h1>Url</h1>

<table>
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>Url</td>
      <td><%= link_to @shortened_url %></td>
    </tr>
  </tbody>
</table>

<br>

app/views/stats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statistics dashboard</h1>

<table>
  <thead>
    <tr>
      <th align='left'>Url</th>
      <th></th>
      <th align='left'>Redirected times</th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |url, count| %>
      <tr>
        <td><%= url %></td>
        <td></td>
        <td><%= count %></td>
      </tr>
    <% end %>
  </tbody>
</table>